applicationGroup=by.pkt
applicationVersion=1.0
#vaadinVersion=13.0.7
##Data convertion
#gsonVersion=2.8.5
##Tests
#junitVersion=4.12
#mockitoVersion=1.10.19
#aspectJVersion=1.9.4
#tngtechDataProviderVersion=1.13.1
#assertJVersion=3.12.2
##>>>>>>>>>>Reporting<<<<<<<<<<<
##Logging
#log4jVersion=1.2.17
##Report portal
#rp_log4jVersion=4.0.1
#rp_agentJunitVersion=4.1.0
##Allure report
#allure_Version=2.10.0
#allure_GradleVersion=2.7.0
#allure_JUnitAdaptorVersion=1.5.4
##Jacoco
#jacoco_Version=0.8.3
##>>>>>>>>>>Database<<<<<<<<<<<
##Derby
#derbyVersion=10.14.2.0
#derbyToolsVersion=10.14.2.0
#derbyClientVersion=10.14.2.0
#
#
